name: kjell&cope

on:
  push:
    branches:
      - main
      - python-feature/*

defaults:
  run:
    working-directory: ./kjell

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python version
        uses: actions/setup-python@v4

      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Set bucket name variable
        run: echo "BUCKET_NAME=${{ env.BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Build with SAM
        run: sam build --use-container

      - name: Deploy to main with SAM
        if: github.ref =='refs/heads/main'
        run: sam deploy --template-file template.yaml --stack-name kjell&cope-python --capabilities CAPABILITY_IAM --parameter-overrides BucketName=${{ env.BUCKET_NAME }}