name: spring&hope

on: push

jobs:
  push_to_registry:
    name: Build and if main push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t poem-ppe:$rev -t latest
          docker tag poem-ppe:$rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2034

      - name: Push Docker image from main branch
        if: github.ref =='refs/heads/main'
        run:  docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2034:poem-ppe:$rev
        run:  docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2034:latest